trigger:
- main

variables:
  azureSubscription: '554ceada-6ce3-4200-8f0e-cfbe286bfbe1'
  webAppName: 'java7095'
  environmentName: 'java7095'

stages:

# ------------------- BUILD STAGE -------------------
- stage: Build
  displayName: "Build stage"
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: "Maven Package and Publish Artifacts"
    pool:
      name: Default
      demands:
        - Agent.Name -equals selft-hosted   # ðŸ‘ˆ MUST HAVE

    steps:
    - task: Maven@4
      displayName: "Maven Package"
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'

    - task: CopyFiles@2
      displayName: "Copy JAR/WAR to staging"
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop


# ------------------- DEPLOY STAGE -------------------
- stage: Deploy
  displayName: "Deploy stage"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: "Deploy to Azure Web App"
    environment: $(environmentName)
    pool:
      name: Default
      demands:
        - Agent.Name -equals selft-hosted   # ðŸ‘ˆ MUST HAVE

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: "Azure Web App Deploy: java7095"
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/*.?(war|jar)'
